### ISSUE TITLE
suggestion: DX improvements

### ISSUE THREAD

**Issue by mathroc** [shipmonk-rnd/doctrine-mysql-index-hints#118]
maybe some helpers, could help set and merge index hints, e.g.:

```php
$query = $result = $em->createQueryBuilder()
    ->select('u.id')
    ->from(User::class, 'u')
    ->andWhere('u.id = 1')
    ->getQuery();

UseIndexHintHandler::forceIndex($query, User::IDX_FOO, User::TABLE_NAME);
UseIndexHintHandler::ignoreIndex($query, Account::IDX_3, Account::TABLE_NAME);

$query->getResult();
```

the helpers methods would:
* always call `$query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, HintDrivenSqlWalker::class)`
* get the already set index hints from the query, add the new one to the list and set it on the query

The helpers could be on `UseIndexHintHandler`, or on a dedicated class (e.g. `ShipMonk\Doctrine\MySql\Hint` so that the call becomes just `Hint::forceIndex($query, User::IDX_FOO, User::TABLE_NAME);`)

what do you think?

**Comment by janedbal** [comment]
Hi, thanks for your suggestion. I dont want to introduce multiple ways to do the same thing within this lib when there is no significant benefit. If you prefer those static helpers, you can easily implement those in your codebase (utilizing `$query->getHints()`). Thank you for understanding.
